### PR TITLE
Add calicoctl pool ST

### PR DESCRIPTION
**Pull request by TrimBiggs**

### CODE REVIEW

**Comment by robbrockbank** [comment]
lgtm once the build passes

**Comment by tomdee** [comment]
What's going on with this PR?

**Comment by TrimBiggs** [comment]
Our STs are currently blocked because the latest version of docker experimental is failing due to changes in libnetwork.  We could update our semaphore config to use a known working version, but ideally we want to use the latest experimental.  This is the failure we are currently seeing: https://github.com/projectcalico/calico-docker/issues/471

**Comment by tomdee** [comment]
This is still failing, not sure why. @TrimBiggs thoughts?

**Comment by TrimBiggs** [comment]
Just rebased off of master and is now passing.

**Comment by tomdee** [comment]
LGTM

**Pull request merged**
