### PR TITLE
Managed plugin

### PR DESCRIPTION
**Pull request by bjwbell**
Add support for Docker network and IPAM managed [plugins](https://docs.docker.com/engine/extend/). 

# Building

To build and enable the network plugin, execute:
```
   cd managed-plugin/network
   make network
   make pluginv2
```

Similarly, to build and enable the IPAM plugin, exectute:
```
   cd managed-plugin/ipam
   make ipam
   make pluginv2
```
# Usage

## Create network
```
    docker network create --driver=calico/network-plugin --ipam-driver=calico/ipam net1
```
## Create workloads
```
     docker run --net net1 --name workload-A -tid busybox
     docker run --net net1 --name workload-B -tid busybox
```
## Test connectivity
```
     docker exec workload-A ping -c 4 workload-B.net1
     docker exec workload-B ping -c 4 workload-A.net1
```
# Release

After building the network and IPAM plugins, to release, execute:
```
    cd managed-plugin/network
    make push
    cd ../ipam
    make push
```

### CODE REVIEW

**Comment by jonathan-kosgei** [comment]
Hi, why hasn't this been merged yet? Can I use this? i.e. to create networks with network policy on swarm?

**Comment by tmjd** [comment]
@jonathan-kosgei I do not know

@tomdee The previous PR #144 that was closed in favor of this one was marked v2.2.0?,  I think it is too late for 2.2 but should this go on the roadmap for 2.3?

**Comment by jonathan-kosgei** [comment]
Okay thanks. Any idea when that might be?

**Comment by tomdee** [comment]
It needs some more testing before we can merge it

**Comment by bjwbell** [comment]
@tomdee Do you want unit tests?

**Comment by bjwbell** [comment]
Closing because of no reply

**Pull request closed without merging**
